name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run UI smoke tests
        run: npx cypress run --spec "cypress/e2e/**/*.cy.js"

      - name: Run UI regression tests
        run: npx cypress run --spec "cypress/e2e/**/*.cy.js"

      - name: Run API tests
        run: npx cypress run --spec "cypress/e2e/api/**/*.cy.js"